spring.application.name=SpringEcom

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/ecom_app?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:Vishal@0789}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:5173}
